write and load

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -15,23 +15,20 @@ jobs:
           echo "FOO=${{ secrets.FOO }}" >> config.env
           echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> config.env
           echo "SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}" >> config.env
-          source config.env
+          
+          if [[ -f config.env ]]; then
+            while read -r line; do
+              echo "$line" >> "$GITHUB_ENV"
+            done < config.env
+          else
+            echo "config.env not found!"
+            exit 1
+          fi
         shell: bash
 
       - name: Use composite action to read and print values
         uses: ./action-sets/docker-2/build-and-push
 
-#      - name: Load config.env into environment
-#        run: |
-#          if [[ -f config.env ]]; then
-#            while read -r line; do
-#              echo "$line" >> "$GITHUB_ENV"
-#            done < config.env
-#          else
-#            echo "config.env not found!"
-#            exit 1
-#          fi
-#        shell: bash
 
       - id: send
         continue-on-error: true
