foo

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -21,6 +21,18 @@ jobs:
       - name: Use composite action to read and print values
         uses: ./action-sets/docker-2/build-and-push
 
+      - name: Load config.env into environment
+        run: |
+          if [[ -f config.env ]]; then
+            while read -r line; do
+              echo "$line" >> "$GITHUB_ENV"
+            done < config.env
+          else
+            echo "config.env not found!"
+            exit 1
+          fi
+        shell: bash
+
       - id: send
         continue-on-error: true
         uses: slackapi/slack-github-action@v2.0.0
